version: '3.4'
services:
  qq:
    image: qq:Shop.DinG.CM
    restart: always
    environment:
      LANG: 'C.UTF-8'
    container_name: ${PWD##*/}-QQ
    volumes:
      - ./qq/config.yml:/app/config.yml
    restart: unless-stopped
  gpt:
    image: gpt:Shop.DinG.CM
    
    restart: always
    environment:
      LANG: 'C.UTF-8'
    container_name: ${PWD##*/}-GPT
    volumes:
      - ./config.cfg:/app/config.cfg
      - ./data:/app/data
      - ./presets:/app/presets
      # - ./fonts:/app/fonts # 如果你想自定义字体，就解除注释
  watchtower: # [可选] 自动更新
    image: containrrr/watchtower
    volumes: # 如果启动失败，请修改下面这条：
      - /var/run/docker.sock:/var/run/docker.sock
